### ISSUE TITLE
Revise the dependencies on `package.json`

### ISSUE THREAD

**Issue by biodavidjm** [dictyBase/frontpage-dictybase#48]
Remove the unnecessary modules.

**Comment by biodavidjm** [comment]
"dependencies": {
  "bower": 
  "grunt": 
  "grunt-cli"
  "grunt-autoprefixer": Just write normal CSS according to the latest W3C specs and Autoprefixer will produce the code for old browsers.
  "grunt-concurrent": to run grunt tasks concurrently
  "grunt-contrib-clean": Clean files and folders
  "grunt-contrib-concat": Concatenate files
  "grunt-contrib-connect": Start a connect web server (???)
  "grunt-contrib-copy": Copy files and folders
  "grunt-contrib-cssmin": Minify CSS
  "grunt-contrib-htmlmin": Minify HTML
  "grunt-contrib-imagemin": Minify images
  "grunt-contrib-jshint": Validate js files with JSHint.
  "grunt-contrib-uglify": Minify files with UglifyJS,
  "grunt-contrib-watch": Monotorize changes in the files (???).
  "grunt-filerev": Renames files for browser caching purposes. Used in the build task
  "grunt-google-cdn": Replace Google CDN references
  "grunt-newer": Configure Grunt tasks to run with newer files only.
  "grunt-ng-annotate": ng-annotate tries to make the code safe for minification automatically by using the Angular long form for dependency injection
  "grunt-svgmin": SVG Optimizer for optimizing SVG vector graphics files. 
  "grunt-usemin": Replaces references from non-optimized scripts, stylesheets and other assets to their optimized version within a set of HTML files (or any templates/views)
  "grunt-wiredep": Inject Bower packages into your source code with Grunt
  "jshint-stylish": Stylish reporter for JSHint
  "load-grunt-tasks": Load multiple grunt tasks using globbing patterns
  "time-grunt": Time how long tasks take
},

"devDependencies": {
// ALL OF THEM NECESSARY FOR TESTING
  "jasmine-core": "^2.1.2",
  "karma": "^0.12.25",
  "karma-coverage": "^0.2.7",
  "karma-firefox-launcher": "^0.1.3",
  "karma-jasmine": "^0.3.0",
  "karma-ng-html2js-preprocessor": "^0.1.2",
  "karma-ng-json2js-preprocessor": "^1.0.0",
  "karma-phantomjs-launcher": "^0.1.4",
  "grunt-karma": "^0.9.0"
}

**Comment by cybersiddhu** [comment]
Lets see, you need these modules so that you could run `grunt build`. Remember none of these actually make it to the browser or in other words not a single piece of these code actually part of the final frontpage. So, its better to trim them down as minimal as possible as use only those that are somehow very influential in producing the final html. The only modules that make it to the frontpage comes through bower, so we also need to have a hard look at it next.

"dependencies": {
  "bower": 
  "grunt": 
  "grunt-cli"
  "grunt-autoprefixer": Just write normal CSS according to the latest W3C specs and Autoprefixer will produce the code for old browsers.  __If you are using bootstrap it is already taking care of cross-browser compatibility, isn't it. So, this one seems to be redundant or if not may be bootstrap should be dumped__.
  "grunt-concurrent": to run grunt tasks concurrently.  __Unless your non-concurrent build takes more than half an hour, there is no advantage in using it__
  "grunt-contrib-clean": Clean files and folders
  "grunt-contrib-concat": Concatenate files
  "grunt-contrib-connect": Start a connect web server (???)  __tell me why you need a webserver to run a build ?__
  "grunt-contrib-copy": Copy files and folders
  "grunt-contrib-cssmin": Minify CSS
  "grunt-contrib-htmlmin": Minify HTML
  "grunt-contrib-imagemin": Minify images  __Unless you are sure what they are doing to your image file, its better to skip this. It might not be doing anything__
  "grunt-contrib-jshint": Validate js files with JSHint. __this is what we do in development__
  "grunt-contrib-uglify": Minify files with UglifyJS,
  "grunt-contrib-watch": Monotorize changes in the files (???). __We use this in development__
  "grunt-filerev": Renames files for browser caching purposes. Used in the build task
  "grunt-google-cdn": Replace Google CDN references __I am not sure it is doing anything useful__
  "grunt-newer": Configure Grunt tasks to run with newer files only.
  "grunt-ng-annotate": ng-annotate tries to make the code safe for minification automatically by using the Angular long form for dependency injection
  "grunt-svgmin": SVG Optimizer for optimizing SVG vector graphics files. 
  "grunt-usemin": Replaces references from non-optimized scripts, stylesheets and other assets to their optimized version within a set of HTML files (or any templates/views)
  "grunt-wiredep": Inject Bower packages into your source code with Grunt __Its done during development__
  "jshint-stylish": Stylish reporter for JSHint  __And why we need it here__
  "load-grunt-tasks": Load multiple grunt tasks using globbing patterns
  "time-grunt": Time how long tasks take __Well we could test it for development__
},

So, the commented modules probably need to have a second look and possibly marked for moving to dev dependencies.

**Comment by biodavidjm** [comment]
#54
